### ISSUE TITLE
ModuleNotFoundError: No module named 'anytree'

### ISSUE THREAD

**Issue by jaztiria99** [mcevoyandy/urdf_to_dh#2] opened 2022-02-24 18:05 UTC
Hi,

I was trying to obtain the DH table of MARA robot from its URDF description at https://github.com/AcutronicRobotics/MARA.

I've cloned this repo and compiled with "colcon". I'm sourcing my ROS 2 distribution (Dashing), this converter workspace and the robot workspace (both workspaces are in /home). Then, I'm trying to run the command to actually make the conversion, based on the README file. I'm typing in the terminal:
```
source /opt/ros/dashing/setup.bash
source urdf_to_dh/install/setup.bash
source ros2_abb_ws/install/setup.bash
ros2 run urdf_to_dh generate_dh --ros-args -p urdf_file="~/ros2_mara_ws/src/mara/mara_description/urdf/mara_robot.urdf"
```

The error I'm obtaining is the following
`ModuleNotFoundError: No module named 'anytree'`

I've installed anytree with "pip", but the same error is appearing.
`pip install anytree`

Does anyone know how to solve this issue?

Thanks,

Jon

**Comment by mcevoyandy** [comment] 2022-03-01 03:24
Do you have multiple python versions installed? maybe you need `pip3 install`?

Here's what I get running the node... although I have to caution you, this repo is still very much in a development stage and has only been tested with a few robots that are striclty serial (i.e. no branching in the kinematic chain).

I'd be curious to know if the DH matches with what you'd expect. I'll (hopefully) be making some updates in the near future as I'll be using this tool again myself shortly.

Cheers

```
DH Parameters: (markdown)
|    | joint                         | parent      | child        |        d |    theta |    r |       alpha |
|---:|:------------------------------|:------------|:-------------|---------:|---------:|-----:|------------:|
|  0 | world_to_base_joint           | world       | base_link    |  0       |  90.0002 | 0    |  90.0002    |
|  1 | joint_bases                   | base_link   | base_robot   |  0       |  90.0002 | 0.04 |   0         |
|  2 | motor1                        | base_robot  | motor1_link  | -0       |  90.0002 | 0    |  90.0002    |
|  3 | motor1_cover_joint            | motor1_link | motor1_cover |  0.05122 |  -0      | 0    | -90.0002    |
|  4 | motor2                        | motor1_link | motor2_link  |  0.21492 |  -0      | 0    | -90.0002    |
|  5 | motor3                        | motor2_link | motor3_link  |  0.109   | -90.0002 | 0.2  |   0         |
|  6 | motor3_cover_joint            | motor3_link | motor3_cover |  0       |   0      | 0    |   0         |
|  7 | motor4                        | motor3_link | motor4_link  | -0.10926 |  90.0002 | 0    |  90.0002    |
|  8 | motor5                        | motor4_link | motor5_link  |  0.30999 |   0      | 0    |  90.0002    |
|  9 | motor5_cover_joint            | motor5_link | motor5_cover | -0.10546 |   0      | 0    |   0         |
| 10 | motor6                        | motor5_link | motor6_link  |  0.0008  |  -0      | 0    | -90.0002    |
| 11 | ee_link                       | motor6_link | ee_link      |  0.14676 |  -0      | 0    |  -0.0458366 |
| 12 | motor6_link-tool0_fixed_joint | motor6_link | tool0        |  0.14676 |  -0      | 0    |  -0.0458366 |
```

**Comment by jaztiria99** [comment] 2022-03-02 07:32
Yes, I have Python 2 for ROS Melodic and Python 3 for ROS 2 Dashing. So I imagine the error is in there, as you said. I'll try with `pip3 install`. 

I'll test the provided DH table in the following weeks and I'll let you know.

Thank you very much for your support.

**Comment by mcevoyandy** [comment] 2022-03-09 01:27
Assuming the issue is resolved with pip3 install

**Closed as completed by mcevoyandy** 2022-03-09 01:27 UTC
